# ______________ INSTITUIÇÕES ______________

### Get all
GET http://localhost:3000/instituicao

### Get by id
GET http://localhost:3000/instituicao/1

### Get by id
GET http://localhost:3000/instituicao/metodo/1

###
POST http://localhost:3000/instituicao
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Put by id
PATCH http://localhost:3000/instituicao/1
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Delet by id
DELETE  http://localhost:3000/instituicao/1






# ______________ METODOS ______________

### Get all
GET http://localhost:3000/metodo/distinto

### Get by id
GET http://localhost:3000/metodo/1

###
POST http://localhost:3000/metodo
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Put by id
PATCH http://localhost:3000/metodo/1
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Delet by id
DELETE  http://localhost:3000/metodo/1






# ______________ CONTA ______________

###
POST http://localhost:3000/conta
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Get all of one user id
GET http://localhost:3000/conta/id/1

### Get all of one user id
GET http://localhost:3000/conta/1

### Get by id
GET http://localhost:3000/conta/1/123

### Put by id
PATCH http://localhost:3000/conta/1
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Delet by id
DELETE  http://localhost:3000/conta/1






# ______________ boletos banco do brasil ______________

### Get all of one user id
GET http://localhost:3000/bancobrasil-boleto/1

### Get all of one user id
GET http://localhost:3000/bancobrasil-boleto/cliente/1

###
POST http://localhost:3000/bancobrasil-boleto
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Put by id
PATCH http://localhost:3000/bancobrasil-boleto/1
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Delet by id
DELETE  http://localhost:3000/bancobrasil-boleto/1






# ______________ boletos registrados banco do brasil ______________

### Get all of one user id
GET http://localhost:3000/bancobrasil-boleto-registro/id/1

### Get all of one user id
GET http://localhost:3000/bancobrasil-boleto-registro/123

###
POST http://localhost:3000/bancobrasil-boleto-registro
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Put by id
PATCH http://localhost:3000/bancobrasil-boleto-registro/1
Content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Delet by id
DELETE  http://localhost:3000/bancobrasil-boleto-registro/1